### ISSUE TITLE
Corrections pour le premier billet

### ISSUE THREAD

**Issue by antoinentl** [jekyll-fr/jekyll-fr.github.io#5]
Quelques remarques et signalements de coquilles concernant le [premier billet](http://jekyll-fr.org/2016/04/01/lancement/) du blog :

- questionnement concernant l'expression "gestionnaires de fichiers statiques", "générateurs de site statique" ne serait-il pas plus juste ?
- idem avec " gestionnaires de fichiers statiques" ;
- idem avec "gestionnaires de contenu statique" ;
- remplacer "contributiion" par "contribution" ;
- et sinon merci pour cette belle initiative !

**Comment by DirtyF** [comment]
merci @antoinentl tes retours ont été pris en compte.

Il y a désormais un lien en bas de chaque article pour permettre de corriger :pencil2:  directement depuis Github :octocat:
